version: '3.8'

services:
  web:
    build: .
    container_name: quiz-web-app
    ports:
      - "8080:8080"
    environment:
      # Dùng biến ${DB_PASSWORD} ở đây
      - ConnectionStrings__DefaultConnection=Server=db;Database=LearningPlatform;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=True
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql-learning-platform
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      # Dùng biến ${DB_PASSWORD} ở đây
      - SA_PASSWORD=${DB_PASSWORD} 
    volumes:
      - sql-data:/var/opt/mssql

  kafka:
    image: apache/kafka:3.7.0
    container_name: quiz-kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: quiz-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: quiz-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  vector:
    image: timberio/vector:0.36.0-alpine
    container_name: quiz-vector
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
    depends_on:
      - kafka
      - elasticsearch

volumes:
  sql-data:
  es-data:

